name: CMake

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: "ubuntu 20.04 with gcc",
            os: ubuntu-20.04,
            cc: "gcc",
            cxx: "g++",
          }
          - {
            name: "ubuntu 18.04 with gcc",
            os: ubuntu-18.04,
            cc: "gcc",
            cxx: "g++",
          }
          - {
            name: "ubuntu 20.04 with clang",
            os: ubuntu-20.04,
            cc: "clang",
            cxx: "clang++",
          }
          - {
            name: "ubuntu 18.04 with clang",
            os: ubuntu-18.04,
            cc: "clang",
            cxx: "clang++",
          }
          - {
            name: "macos-11 clang",
            os: macos-11,
            cc: "clang",
            cxx: "clang++",
          }
          - {
            name: "macos-10.15 clang",
            os: macos-10.15,
            cc: "clang",
            cxx: "clang++",
          }

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}

    steps:
      - uses: actions/checkout@v2
      - name: buildtools on ubuntu
        if: startsWith(matrix.config.name, 'ubuntu')
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libboost-all-dev
      - name: buildtools on macos
        if: startsWith(matrix.config.name, 'macos')
        shell: bash
        run: |
          brew install boost
      - name: build
        shell: bash
        run: |
          cmake -S .github/workflows/cmake-superbuild  -B build
          cmake --build build

